openapi: 3.0.0

components:
  responses:
    search_api:
      description: Everything is working fine
      content:
        application/json:
          schema:
            title: SearchResponse
            type: object
            properties:
              result:
                type: array
                maxitems: 100
                items:
                  type: object
                  title: Case
                  properties:
                    case_id:
                      type: string
                      example: FNDBUHRQIEZEWFYXNEZWXBTJLZJQ40930
                    case_number:
                      type: string
                      example: 18STFL06463
                    case_name:
                      type: string
                      example: PATTON, TARYN VS PATTON, JONATHAN
                    case_name_snippet:
                      type: string
                      example: <b>PATTON, TARYN VS PATTON, JONATHAN</b>
                    filing_date:
                      type: string
                      format: date
                      pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}$
                      example: "2018-05-25"
                    case_first_fetch:
                      type: string
                      format: date time
                      pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$
                      example: "2017-11-15 05:47:44"
                    case_last_fetch:
                      type: string
                      format: date time
                      pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$
                      example: "2018-05-25 05:47:44"
                    case_last_updates_found:
                      description: The date and time when the case was last fetched from the Court where we found changes in the case information. Use this field to compare with the case information cached in your database to decide whether case has updates. This date and time is in UTC. Formatted as YYYY-MM-DD HH:MM:SS
                      type: string
                      format: date time
                      pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$
                      example: "2018-04-20 05:47:44"
                    case_type:
                      type: object
                      title: Case Type
                      properties:
                        name:
                          type: string
                          example: Civil
                        abbreviation:
                          type: string
                          exmaple: CV
                        id:
                          type: integer
                          example: 8
                        level:
                          type: integer
                          exmaple: 1
                        child:
                          type: object
                          title: Child
                          properties:
                            name:
                              type: string
                              example: Family
                            abbreviation:
                              type: string
                              exmaple: CV-FM
                            id:
                              type: integer
                              example: 206
                            level:
                              type: integer
                              exmaple: 2
                            child:
                              title: Child
                              type: object
                              properties:
                                name:
                                  type: string
                                  example: Marriage Dissolution/Divorce
                                abbreviation:
                                  type: string
                                  exmaple: CV-FM-MD
                                id:
                                  type: integer
                                  example: 2197
                                level:
                                  type: integer
                                  exmaple: 3
                    case_status:
                      type: object
                      title: Case Status
                      properties:
                        name:
                          type: string
                          example: Pending
                        abbreviation:
                          type: string
                          exmaple: PD
                        id:
                          type: integer
                          example: 25
                        level:
                          type: integer
                          exmaple: 1
                        child:
                          type: object
                          title: Child
                          properties:
                            name:
                              type: string
                              example: Other Pending
                            abbreviation:
                              type: string
                              exmaple: PD-OTH
                            id:
                              type: integer
                              example: 526
                            level:
                              type: integer
                              exmaple: 2
                    jurisdiction:
                      type: object
                      title: Jurisdiction
                      properties:
                        name:
                          type: string
                          example: State
                        abbreviation:
                          type: string
                          exmaple: ST
                        id:
                          type: integer
                          example: 2
                        level:
                          type: integer
                          exmaple: 1
                        child:
                          type: object
                          title: Child
                          properties:
                            name:
                              type: string
                              example: California
                            abbreviation:
                              type: string
                              exmaple: ST-CA
                            id:
                              type: integer
                              example: 129
                            level:
                              type: integer
                              exmaple: 2
                            child:
                              title: Child
                              type: object
                              properties:
                                name:
                                  type: string
                                  example: Los Angeles County Superior Courts
                                abbreviation:
                                  type: string
                                  exmaple: ST-CA-LASC
                                id:
                                  type: integer
                                  example: 32774
                                level:
                                  type: integer
                                  exmaple: 3
                                child:
                                  title: Child
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                      example: Stanley Mosk Courthouse
                                    abbreviation:
                                      type: string
                                      exmaple: ST-CA-LASC-SMC
                                    id:
                                      type: integer
                                      example: 131162
                                    level:
                                      type: integer
                                      exmaple: 4
                    attorneys:
                      maxitems: 3
                      type: array
                      items:
                        type: object
                        title: Attorney
                        properties:
                          fullname:
                            type: string
                            example: TRIEU JOHN D. ESQ.
                          fullname_snippet:
                            type: string
                            example: TRIEU <b>JOHN</b> D. ESQ.
                          attorney_type:
                            type: object
                            title: Attorney Type
                            properties:
                              name:
                                type: string
                                example: Attorney
                              id:
                                type: integer
                                example: 53
                              abbreviation:
                                type: string
                                exampple: ATR
                          firm:
                            type: string
                            example: null
                          firm_snippet:
                            type: string
                            example: null
                    parties:
                      type: array
                      maxitems: 3
                      items:
                        type: object
                        title: Party
                        properties:
                          fullname:
                            type: string
                            example: CHUNG JOHN JIYUN
                          fullname_snippet:
                            type: string
                            example: CHUNG <b>JOHN</b> JIYUN
                          party_type:
                            type: object
                            title: Party Type
                            properties:
                              name:
                                type: string
                                example: Petitioner
                              id:
                                type: integer
                                example: 832
                              abbreviation:
                                type: string
                                exampple: PTR
                          entity_type:
                            type: string
                            example: Company
                          representation:
                            type: object
                            title: Representation
                            properties:
                              name:
                                type: string
                                example: Attorney Represented
                              id:
                                type: integer
                                example: 38
                              abbreviation:
                                type: string
                                exampple: ATTREP
                    judges:
                      type: array
                      maxitems: 3
                      items:
                        type: object
                        title: Judge
                        properties:
                          fullname:
                            type: string
                            example: CHEMELESKI, JOHN
                          fullname_snippet:
                            type: string
                            example: CHEMELESKI, <b>JOHN</b>
                          judge_type:
                            type: object
                            title: Judge Type
                            properties:
                              name:
                                type: string
                                example: Judge
                              id:
                                type: integer
                                example: 69
                              abbreviation:
                                type: string
                                exampple: JDG
                    dockets:
                      type: array
                      maxitems: 3
                      items:
                        type: object
                        title: Docket
                        properties:
                          docket_number:
                            type: integer
                            exmaple: 402
                          text:
                            type: string
                            example: "2018-05-25 Request - DV Prevention w/Minor Child (w/in Existing Case); Filed by Petitioner! 2018-05-25 Petition - Dissolution w/ Minor Child; Filed by Petitioner! 2018-05-25 Notice
                                                              - Case Assignment! 2018-05-25 <b>Order</b> - Financial Information (FAM 111)"
                          date:
                            type: date
                            pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}$
                            example: "2018-05-25"
                          document_count:
                            type: integer
                            example: 5
              items_per_page:
                description: Request data will be returned.
                type: integer
                example: 10
              page:
                description: Request data will be returned.
                type: integer
                example: 1
              total_matches:
                description: The number of matches that found in the index.
                type: integer
                example: 1